export const ROLES = [
    { Deportment: "ENGINEERING", Role: "Backend" },
    { Deportment: "ENGINEERING", Role: "Frontend" },
    { Deportment: "ENGINEERING", Role: "IOS" },
    { Deportment: "ENGINEERING", Role: "Fullstack" },
    { Deportment: "ENGINEERING", Role: "Flutter" },
    { Deportment: "ENGINEERING", Role: "React Native" },
    { Deportment: "ENGINEERING", Role: "Android" },
    { Deportment: "ENGINEERING", Role: "Tech Lead" },
    { Deportment: "DESIGN", Role: "Designer" },
    { Deportment: "DESIGN", Role: "Design Manager" },
    { Deportment: "DESIGN", Role: "Product Designer" },
    { Deportment: "DESIGN", Role: "Graphic Designer" },
    { Deportment: "PRODUCT", Role: "Product Manager" },
    { Deportment: "OPERATIONS", Role: "Operations Manager" },
    { Deportment: "OPERATIONS", Role: "Founder's Office/Chief Of Staff" },
    { Deportment: "SALES", Role: "Sales Development" },
    { Deportment: "SALES", Role: "Account Executive" },
    { Deportment: "SALES", Role: "Account Manager" },
    { Deportment: "MARKETING", Role: "Digital Marketing Manager" },
    { Deportment: "MARKETING", Role: "Growth Hacker" },
    { Deportment: "MARKETING", Role: "Marketing" },
    { Deportment: "MARKETING", Role: "Product Marketing Manager" },
  ];
  
  export const DATA = {
    "Location": [
      "Delhi Ncr",
      "Mumbai",
      "Chennai",
      "Bangalore",
      "Hyderabard",
      "Pune",
    ],
    "Experience": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
    "Remote": ["Remote", "Hybrid", "In-office"],
    "Minimum Base Pay Salary": [
      "0L",
      "10L",
      "20L",
      "30L",
      "40L",
      "50L",
      "60L",
      "70L",
    ],
  };